name: 'ecommerce_dbt'
version: '1.0.0'
profile: 'ecommerce_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:
    staging:
      raw:
        +materialized: view
    intermediate:
      +materialized: view  
    mart:
      +materialized: view  
    # No +schema override here to avoid doubling schema prefix
