services:
  db:
    container_name: postgres_container
    image: postgres:14.17
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data  
    networks:
      - my-network 
    healthcheck:  # ✅ Marks DB as healthy once ready
      test: ["CMD-SHELL", "pg_isready -U db_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5 

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_container
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ecommerce_dbt:/usr/app  
      - ~/.dbt:/root/.dbt    
    working_dir: /usr/app
    command: ["run"]

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset_container
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "testing_key"
      PYTHONPATH: "/app/pythonpath:/app"
    volumes:
      - ./superset_home:/app/superset_home
    depends_on:
      - db
    networks:
      - my-network
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debug
      "


networks:
  my-network:
    driver: bridge    
