services:
  db:
    container_name: postgres_container
    image: postgres:14.17
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data  
    networks:
      - my-network 
    healthcheck:  # ✅ Marks DB as healthy once ready
      test: ["CMD-SHELL", "pg_isready -U db_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5   
networks:
  my-network:
    driver: bridge    
