name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push DBT and Superset Docker Images
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Step 2: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # ✅ Step 3: Build DBT Image
      - name: Build DBT Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dbt-ecommerce-dbt:latest \
            -f ecommerce-dbt/Dockerfile \
            ecommerce-dbt

      # ✅ Step 4: Run DBT test
      - name: Run dbt test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/ecommerce-dbt:/usr/app \
            -v ${{ github.workspace }}/.dbt:/root/.dbt \
            -e DBT_PROFILES_DIR=/usr/app/profiles \
            dbt-ecommerce-dbt dbt test      

      # ✅ Step 5: Push DBT Image
      - name: Push DBT Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dbt-ecommerce-dbt:latest

      # ✅ Step 6: Build Superset Image
      - name: Build Superset Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/superset-ecommerce-dbt:latest \
            -f ecommerce-dbt/Dockerfile.superset \
            ecommerce-dbt

      # ✅ Step 7: Push Superset Image
      - name: Push Superset Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/superset-ecommerce-dbt:latest

      # ✅ Step 8: Upload docker-compose.yml
      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: ecommerce-dbt/docker-compose.yml
